"""Re-ID router — POST /reid/extract and POST /reid/match endpoints.

Provides body appearance embedding extraction and cross-camera matching
for person re-identification without face visibility.
"""

import base64
import logging

import cv2
import numpy as np
from fastapi import APIRouter, HTTPException

from models.schemas import ReIDRequest, ReIDResponse, ReIDMatch
from services.reid import (
    add_to_gallery,
    extract_clothing_colors,
    extract_embedding,
    estimate_height,
    get_gallery_stats,
    is_loaded,
    match_cross_camera,
)

logger = logging.getLogger("ai-sidecar.reid_router")
router = APIRouter(tags=["reid"])


@router.post("/reid/extract", response_model=ReIDResponse)
async def reid_extract(request: ReIDRequest) -> ReIDResponse:
    """Extract body embedding from a person crop and store in gallery.

    Also performs cross-camera matching against existing gallery entries
    from other cameras to assign a global_person_id.
    """
    if not is_loaded():
        raise HTTPException(status_code=503, detail="Re-ID model not loaded")

    if not request.crop_base64:
        raise HTTPException(status_code=400, detail="crop_base64 is required")

    try:
        img_bytes = base64.b64decode(request.crop_base64)
        nparr = np.frombuffer(img_bytes, np.uint8)
        person_crop = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        if person_crop is None:
            raise HTTPException(status_code=400, detail="Failed to decode person crop image")

        # Extract body embedding
        embedding = extract_embedding(person_crop)

        # Try cross-camera match first
        match_result = match_cross_camera(
            source_camera_id=request.camera_id,
            embedding=embedding,
            exclude_track_id=request.track_id,
        )

        # Determine global_person_id
        if match_result["matched"]:
            global_person_id = match_result["global_person_id"]
        else:
            global_person_id = None  # Will be generated by add_to_gallery

        # Add to gallery (generates global_person_id if None)
        assigned_gid = add_to_gallery(
            camera_id=request.camera_id,
            track_id=request.track_id,
            embedding=embedding,
            global_person_id=global_person_id,
            timestamp=request.timestamp,
        )

        return ReIDResponse(
            body_embedding=embedding.tolist(),
            match=ReIDMatch(
                global_person_id=assigned_gid,
                person_id=match_result.get("person_id"),
                similarity=match_result["similarity"],
                matched=match_result["matched"],
            ),
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error("Re-ID extraction failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Re-ID extraction failed: {e}")


@router.post("/reid/match", response_model=ReIDMatch)
async def reid_match(request: ReIDRequest) -> ReIDMatch:
    """Match a person crop against the cross-camera gallery without storing.

    Used for checking if a person on one camera has been seen on another
    camera without updating the gallery.
    """
    if not is_loaded():
        raise HTTPException(status_code=503, detail="Re-ID model not loaded")

    if not request.crop_base64:
        raise HTTPException(status_code=400, detail="crop_base64 is required")

    try:
        img_bytes = base64.b64decode(request.crop_base64)
        nparr = np.frombuffer(img_bytes, np.uint8)
        person_crop = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        if person_crop is None:
            raise HTTPException(status_code=400, detail="Failed to decode person crop image")

        embedding = extract_embedding(person_crop)

        match_result = match_cross_camera(
            source_camera_id=request.camera_id,
            embedding=embedding,
            exclude_track_id=request.track_id,
        )

        return ReIDMatch(
            global_person_id=match_result.get("global_person_id"),
            person_id=match_result.get("person_id"),
            similarity=match_result["similarity"],
            matched=match_result["matched"],
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error("Re-ID match failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Re-ID match failed: {e}")


@router.get("/reid/gallery/stats")
async def reid_gallery_stats() -> dict:
    """Get Re-ID gallery statistics (total entries, per-camera counts)."""
    return get_gallery_stats()
